<a href="https://colab.research.google.com/github/midhatkamal5/AssignmentTemperatureApp/blob/main/Temperature.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ML Assignment 2**

In [3]:
import numpy as np

#Task 1 - Generate random daily temperature values for 30 days (28 days considered for settlement), ranging from 15°C to 35°C.
array=np.random.randint(15,35,28)
print(f"Array of temperature values is: {array}")
print()

#Task 2 - Calculate the average, maximum, and minimum temperatures for the entire month.
arrayMaximum = np.max(array)
print(f"Maximum is: {arrayMaximum}")
print()

arrayMinimum = np.min(array)
print(f"Minimum is: {arrayMinimum}")
print()

arrayAverage = np.average(array)
print(f"Average is: {arrayAverage}")
print()

#Task 3 - Identify the number of days when the temperature exceeds 30°C (considered as hot days).
hotDays = np.sum(array > 30)
print(f"Number of hot days are: {hotDays}")
print()

#Task 4- Determine the hottest day of the month, based on the highest temperature recorded.
indexOfHottestDay = np.argmax(array)
print(f"Hottest Day index: {indexOfHottestDay}")
print()

#Task 5 - Reshape the daily temperatures into weekly data for better analysis (consider 4 weeks with 7 days each).
arrayReshaped = array.reshape(4,7)
print("Reshaped Array of temperature values is as follows:")
print(f"{arrayReshaped}")
print()

#Task 6 - Calculate the total temperature and average temperature for each week.
print("Weekly Total and Average temperature is as follows: ")
totalWeekly = np.sum(arrayReshaped, axis=1)
AverageWeekly = np.mean(arrayReshaped, axis=1)

for i in range(arrayReshaped.shape[0]):
    print(f"Week {i+1}:")
    print(f"Total Temperature: {totalWeekly[i]:.2f}")
    print(f"Average Temperature: {AverageWeekly[i]:.2f}")
    print()


Array of temperature values is: [16 30 30 30 31 30 30 25 15 16 26 21 30 18 18 17 33 20 21 23 16 15 32 30
 21 21 27 25]

Maximum is: 33

Minimum is: 15

Average is: 23.821428571428573

Number of hot days are: 3

Hottest Day index: 16

Reshaped Array of temperature values is:
[[16 30 30 30 31 30 30]
 [25 15 16 26 21 30 18]
 [18 17 33 20 21 23 16]
 [15 32 30 21 21 27 25]]

Weekly Total and Average temperature is: 
Week 1:
Total Temperature: 197.00
Average Temperature: 28.14

Week 2:
Total Temperature: 151.00
Average Temperature: 21.57

Week 3:
Total Temperature: 148.00
Average Temperature: 21.14

Week 4:
Total Temperature: 171.00
Average Temperature: 24.43

